Portfolio mobile version
ridabensalem/Portfloio-website- pull request #5
Opened 2022-12-06 21:35 UTC by ridabensalem

### Portfolio mobile version

 in this version we :

- added the works section
- added about my self section
- added buttons actions

2022-12-06 22:04 UTC, emmiiorji requested changes
Hi @ridabensalem, 
# Status: Changes Required ♻️

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![A little bit more](https://user-images.githubusercontent.com/20554583/206012986-996f3817-a0bb-4103-acf4-72c95e9ef4d7.gif)

## Good Highlights✔️

- Linter checks are passing
- Good commit messages
- Adhered to GitHub flow


## Required Changes ♻️
_Check the comments under the review._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-06 22:04 UTC, emmiiorji commented on index.html
> +                                </ul>
Well done for rightly using the ul and li tags for representing the languages and skills. Kindly add some margin between the languages and frameworks to match the design. 

Also, kindly change the second `framework` to `skills`.

Your design:
![image](https://user-images.githubusercontent.com/20554583/206031990-ccff6a8e-4a49-47b5-a612-f3ca6194b91b.png)


Figma design:
![image](https://user-images.githubusercontent.com/20554583/206032973-eaf8e0bf-60d0-47ea-9631-668cadcac961.png)

2022-12-06 22:04 UTC, emmiiorji commented on index.html
> +                                    A daily selection of privately personalized reads; no accounts or sign-ups required.
Kindly reduce the margin between the cards a little bit in order to match the design template.

Your design:
![image](https://user-images.githubusercontent.com/20554583/206032330-51c4e6de-eee3-4f52-9e50-c8161bff4e11.png)


Figma design:
![image](https://user-images.githubusercontent.com/20554583/206032355-039b4b81-bfcc-4560-b881-dfe8320f6f1a.png)

2022-12-07 08:20 UTC, ridabensalem commented on index.html
> +                                </ul>
I have applied everything you have suggested Thank you

2022-12-07 08:29 UTC, Nyame-Wolf approved these changes
# STATUS: APPROVED :heavy_check_mark: :green_circle: 

Hi @ridabensalem  :smile: , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
![](https://media.giphy.com/media/YKdm91XONLTaw/giphy.gif)


## Highlights :sparkles:
- Linters are passing
- Great work using correct github flow
- Great communication with reviewer.

## Optional suggestions :ballot_box_with_check: 

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

APPROVED! 💯 💯 💯

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me, @Nyame-Wolf in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-07 08:29 UTC, Nyame-Wolf commented on index.html
> +                  <div class="card-works">
[OPTIONAL] I suggest you use the semantic tags `<article>`. A `div` tag is pretty general. This cards represent standalone parts of the application and they are articles of the section. It makes your code better and friendlier to screen readers

2022-12-07 10:04 UTC, merged